// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NpTest.Data;

#nullable disable

namespace NpTest.Migrations
{
    [DbContext(typeof(BiddingContext))]
    [Migration("20231124004441_AdminPasswordHash")]
    partial class AdminPasswordHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("NpTest.Models.Bidding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OpenDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Bidding", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "First bidding",
                            Number = 1,
                            OpenDate = new DateTime(2023, 11, 23, 21, 44, 41, 361, DateTimeKind.Local).AddTicks(5472),
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Second bidding",
                            Number = 2,
                            OpenDate = new DateTime(2023, 11, 23, 21, 44, 41, 361, DateTimeKind.Local).AddTicks(5483),
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            Description = "Third bidding",
                            Number = 3,
                            OpenDate = new DateTime(2023, 11, 23, 21, 44, 41, 361, DateTimeKind.Local).AddTicks(5484),
                            Status = 0
                        });
                });

            modelBuilder.Entity("NpTest.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Password = "$2a$04$zF53nha18AKyqWRwVlk87ueW2m0w2w81WGOhzWw.aVrqUvcBXOwEu",
                            UpdatedAt = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserName = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
