// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NpTest.Data;

#nullable disable

namespace NpTest.Migrations
{
    [DbContext(typeof(BiddingContext))]
    partial class BiddingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("NpTest.Models.Bidding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OpenDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Bidding", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "First bidding",
                            Number = 1,
                            OpenDate = new DateTime(2023, 11, 21, 18, 56, 3, 556, DateTimeKind.Local).AddTicks(7850),
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Second bidding",
                            Number = 2,
                            OpenDate = new DateTime(2023, 11, 21, 18, 56, 3, 556, DateTimeKind.Local).AddTicks(7860),
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            Description = "Third bidding",
                            Number = 3,
                            OpenDate = new DateTime(2023, 11, 21, 18, 56, 3, 556, DateTimeKind.Local).AddTicks(7861),
                            Status = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
